export const TOGGLE_BOOKING_MODAL = 'TOGGLE_BOOKING_MODAL';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const NEW_BOOKING_RESPONSE = 'NEW_BOOKING_RESPONSE';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';
