export const TOGGLE_BOOKING_MODAL = 'TOGGLE_BOOKING_MODAL';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const NEW_BOOKING_RESPONSE = 'NEW_BOOKING_RESPONSE';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';

export const BOOKING_INFO = 'BOOKING_INFO';

export const CHARGE_REQUEST = 'CHARGE_REQUEST';
export const CHARGE_SUCCESS = 'CHARGE_SUCCESS';
export const CHARGE_FAILURE = 'CHARGE_FAILURE';

export const BOOKING_LIST = 'BOOKING_LIST';

export const HOST_BOOKING_LIST_REQUEST = 'HOST_BOOKING_LIST_REQUEST';
export const HOST_BOOKING_LIST_SUCCESS = 'HOST_BOOKING_LIST_SUCCESS';
export const HOST_BOOKING_LIST_FAILURE = 'HOST_BOOKING_LIST_FAILURE';

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';


export const TOGGLE_BOOKING_DATE_EDIT_MODAL = 'TOGGLE_BOOKING_DATE_EDIT_MODAL';

export const CHANGE_DATE_REQUEST = 'CHANGE_DATE_REQUEST';
export const CHANGE_DATE_SUCCESS = 'CHANGE_DATE_SUCCESS';
export const CHANGE_DATE_FAILURE = 'CHANGE_DATE_FAILURE';


export const TOGGLE_INVENTORY_MODAL = 'TOGGLE_INVENTORY_MODAL';

export const ADD_INVENTORY_REQUEST = 'ADD_INVENTORY_REQUEST';
export const ADD_INVENTORY_SUCCESS = 'ADD_INVENTORY_SUCCESS';
export const ADD_INVENTORY_FAILURE = 'ADD_INVENTORY_FAILURE';

export const TOGGLE_BOOKING_TERMS_MODAL = 'TOGGLE_BOOKING_TERMS_MODAL';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';


export const SIGN_IN_HOST_REQUEST = 'SIGN_IN_HOST_REQUEST';
export const SIGN_IN_HOST_SUCCESS = 'SIGN_IN_HOST_SUCCESS';
export const SIGN_IN_HOST_FAILURE = 'SIGN_IN_HOST_FAILURE';


export const TOGGLE_BOOKING_TERMS_MODAL_HOST = 'TOGGLE_BOOKING_TERMS_MODAL_HOST';


export const TOGGLE_INVENTORY_VIEW_MODAL = 'TOGGLE_INVENTORY_VIEW_MODAL';


export const GUEST_PAYMENT_REQUEST = 'GUEST_PAYMENT_REQUEST';
export const GUEST_PAYMENT_SUCCESS = 'GUEST_PAYMENT_SUCCESS';
export const GUEST_PAYMENT_FAILURE = 'GUEST_PAYMENT_FAILURE';


export const HOST_PAYMENT_REQUEST = 'HOST_PAYMENT_REQUEST';
export const HOST_PAYMENT_SUCCESS = 'HOST_PAYMENT_SUCCESS';
export const HOST_PAYMENT_FAILURE = 'HOST_PAYMENT_FAILURE';


export const CANCEL_BOOKING_HOST_REQUEST = 'CANCEL_BOOKING_HOST_REQUEST';
export const CANCEL_BOOKING_HOST_SUCCESS = 'CANCEL_BOOKING_HOST_SUCCESS';
export const CANCEL_BOOKING_HOST_FAILURE = 'CANCEL_BOOKING_HOST_FAILURE';

export const CANCEL_BOOKING_GUEST_REQUEST = 'CANCEL_BOOKING_GUEST_REQUEST';
export const CANCEL_BOOKING_GUEST_SUCCESS = 'CANCEL_BOOKING_GUEST_SUCCESS';
export const CANCEL_BOOKING_GUEST_FAILURE = 'CANCEL_BOOKING_GUEST_FAILURE';



export const TOGGLE_CANCEL_HOST_BOOKING_MODAL = 'TOGGLE_CANCEL_HOST_BOOKING_MODAL';
export const TOGGLE_CANCEL_GUEST_BOOKING_MODAL = 'TOGGLE_CANCEL_GUEST_BOOKING_MODAL';

export const BOOKING_COUNT_REQUEST = 'BOOKING_COUNT_REQUEST';
export const BOOKING_COUNT_SUCCESS = 'BOOKING_COUNT_SUCCESS';
export const BOOKING_COUNT_FAILURE = 'BOOKING_COUNT_FAILURE';


export const TERMS_REQUEST = 'TERMS_REQUEST';
export const TERMS_SUCCESS = 'TERMS_SUCCESS';
export const TERMS_FAILURE = 'TERMS_FAILURE';


export const COUPON_REQUEST = 'COUPON_REQUEST';
export const COUPON_SUCCESS = 'COUPON_SUCCESS';
export const COUPON_FAILURE = 'COUPON_FAILURE';


