export const TOGGLE_BOOKING_MODAL = 'TOGGLE_BOOKING_MODAL';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const NEW_BOOKING_RESPONSE = 'NEW_BOOKING_RESPONSE';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';

export const BOOKING_INFO = 'BOOKING_INFO';

export const CHARGE_REQUEST = 'CHARGE_REQUEST';
export const CHARGE_SUCCESS = 'CHARGE_SUCCESS';
export const CHARGE_FAILURE = 'CHARGE_FAILURE';

export const BOOKING_LIST = 'BOOKING_LIST';

export const HOST_BOOKING_LIST_REQUEST = 'HOST_BOOKING_LIST_REQUEST';
export const HOST_BOOKING_LIST_SUCCESS = 'HOST_BOOKING_LIST_SUCCESS';
export const HOST_BOOKING_LIST_FAILURE = 'HOST_BOOKING_LIST_FAILURE';

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_FAILURE = 'UPDATE_BOOKING_FAILURE';


