export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const GOOGLE_REGISTER_REQUEST = 'GOOGLE_REGISTER_REQUEST';
export const GOOGLE_REGISTER_SUCCESS = 'GOOGLE_REGISTER_SUCCESS';
export const GOOGLE_REGISTER_FAILURE = 'GOOGLE_REGISTER_FAILURE';

export const FACEBOOK_REGISTER_REQUEST = 'FACEBOOK_REGISTER_REQUEST';
export const FACEBOOK_REGISTER_SUCCESS = 'FACEBOOK_REGISTER_SUCCESS';
export const FACEBOOK_REGISTER_FAILURE = 'FACEBOOK_REGISTER_FAILURE';

export const VERIFY_TOKEN_REQUEST = 'VERIFY_TOKEN_REQUEST';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAILURE = 'VERIFY_TOKEN_FAILURE';