export const CHAT_GROUP_REQUEST = 'CHAT_GROUP_REQUEST';
export const CHAT_GROUP_SUCCESS = 'CHAT_GROUP_SUCCESS';
export const CHAT_GROUP_FAILURE = 'CHAT_GROUP_FAILURE';


export const MESSAGE_REQUEST = 'MESSAGE_REQUEST';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_FAILURE = 'MESSAGE_FAILURE';

export const SET_CURRENT_CHATGROUP = 'SET_CURRENT_CHATGROUP';
export const SET_CURRENT_LISTID = 'SET_CURRENT_LISTID';

export const SET_CURRENT_HOST_EMAIL = 'SET_CURRENT_HOST_EMAIL';
export const SET_CURRENT_GUEST_EMAIL = 'SET_CURRENT_GUEST_EMAIL';

export const PUSH_MESSAGE_INTO_LIST = 'PUSH_MESSAGE_INTO_LIST';

export const PUSH_REMOTE_CHAT = 'PUSH_REMOTE_CHAT'; 