export const TOGGLE_NEW_CARD_MODAL = 'TOGGLE_NEW_CARD_MODAL';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';


export const CARD_INFO_REQUEST = 'CARD_INFO_REQUEST';
export const CARD_INFO_SUCCESS = 'CARD_INFO_SUCCESS';
export const CARD_INFO_FAILURE = 'CARD_INFO_FAILURE';


export const ADD_BANK_REQUEST = 'ADD_BANK_REQUEST';
export const ADD_BANK_SUCCESS = 'ADD_BANK_SUCCESS';
export const ADD_BANK_FAILURE = 'ADD_BANK_FAILURE';


export const BANK_LIST_REQUEST = 'BANK_LIST_REQUEST';
export const BANK_LIST_SUCCESS = 'BANK_LIST_SUCCESS';
export const BANK_LIST_FAILURE = 'BANK_LIST_FAILURE';


export const DELETE_BANK_REQUEST = 'DELETE_BANK_REQUEST';
export const DELETE_BANK_SUCCESS = 'DELETE_BANK_SUCCESS';
export const DELETE_BANK_FAILURE = 'DELETE_BANK_FAILURE';


export const TOGGLE_BANK_MODAL = 'TOGGLE_BANK_MODAL';


export const GUEST_PAYMENT_LISTING_REQUEST = 'GUEST_PAYMENT_LISTING_REQUEST';
export const GUEST_PAYMENT_LISTING_SUCCESS = 'GUEST_PAYMENT_LISTING_SUCCESS';
export const GUEST_PAYMENT_LISTING_FAILURE = 'GUEST_PAYMENT_LISTING_FAILURE';


export const HOST_PAYMENT_LISTING_REQUEST = 'HOST_PAYMENT_LISTING_REQUEST';
export const HOST_PAYMENT_LISTING_SUCCESS = 'HOST_PAYMENT_LISTING_SUCCESS';
export const HOST_PAYMENT_LISTING_FAILURE = 'HOST_PAYMENT_LISTING_FAILURE';

export const SET_DEFAULT_BANK_REQUEST = 'SET_DEFAULT_BANK_REQUEST';
export const SET_DEFAULT_BANK_SUCCESS = 'SET_DEFAULT_BANK_SUCCESS';
export const SET_DEFAULT_BANK_FAILURE = 'SET_DEFAULT_BANK_FAILURE';

