export const STEP_ONE_SAVE = 'STEP_ONE_SAVE';
export const STEP_TWO_SAVE = 'STEP_TWO_SAVE';

export const STEP_THREE_SAVE_REQUEST = 'STEP_THREE_SAVE_REQUEST';
export const STEP_THREE_SAVE_SUCCESS = 'STEP_THREE_SAVE_SUCCESS';
export const STEP_THREE_SAVE_FAILURE = 'STEP_THREE_SAVE_FAILURE';

export const STEP_THREE_UPDATE_CLIENT = 'STEP_THREE_UPDATE_CLIENT';


export const STEP_FOUR_SAVE_REQUEST = 'STEP_FOUR_SAVE_REQUEST';
export const STEP_FOUR_SAVE_SUCCESS = 'STEP_FOUR_SAVE_SUCCESS';
export const STEP_FOUR_SAVE_FAILURE = 'STEP_FOUR_SAVE_FAILURE';

export const STEP_FOUR_UPDATE_CLIENT = 'STEP_FOUR_UPDATE_CLIENT';


export const STEP_FIVE_SAVE_REQUEST = 'STEP_FIVE_SAVE_REQUEST';
export const STEP_FIVE_SAVE_SUCCESS = 'STEP_FIVE_SAVE_SUCCESS';
export const STEP_FIVE_SAVE_FAILURE = 'STEP_FIVE_SAVE_FAILURE';
export const STEP_FIVE_UPDATE_CLIENT = 'STEP_FIVE_UPDATE_CLIENT';

export const CLEAR_MESSAGE_FIELDS = 'CLEAR_MESSAGE_FIELDS';


export const STEP_SIX_UPDATE_CLIENT = 'STEP_SIX_UPDATE_CLIENT';


export const GUEST_REQUEST = 'GUEST_REQUEST';
export const GUEST_SUCCESS = 'GUEST_SUCCESS';
export const GUEST_FAILURE = 'GUEST_FAILURE';

export const GUEST_ACCESS_REQUEST = 'GUEST_ACCESS_REQUEST';
export const GUEST_ACCESS_SUCCESS = 'GUEST_ACCESS_SUCCESS';
export const GUEST_ACCESS_FAILURE = 'GUEST_ACCESS_FAILURE';

export const UPDATE_COORDINATES_CLIENT = 'UPDATE_COORDINATES_CLIENT';

export const SET_MANUAL_COORDINATES = 'SET_MANUAL_COORDINATES';








export const SPACE_TYPE_REQUEST = 'SPACE_TYPE_REQUEST';
export const SPACE_TYPE_SUCCESS = 'SPACE_TYPE_SUCCESS';
export const SPACE_TYPE_FAILURE = 'SPACE_TYPE_FAILURE';

export const SPACE_USED_FOR_REQUEST = 'SPACE_USED_FOR_REQUEST';
export const SPACE_USED_FOR_SUCCESS = 'SPACE_USED_FOR_SUCCESS';
export const SPACE_USED_FOR_FAILURE = 'SPACE_USED_FOR_FAILURE';


export const FEATURE_REQUEST = 'FEATURE_REQUEST';
export const FEATURE_SUCCESS = 'FEATURE_SUCCESS';
export const FEATURE_FAILURE = 'FEATURE_FAILURE';


export const FLOOR_REQUEST = 'FLOOR_REQUEST';
export const FLOOR_SUCCESS = 'FLOOR_SUCCESS';
export const FLOOR_FAILURE = 'FLOOR_FAILURE';


export const GET_COORDINATES_REQUEST = 'GET_COORDINATES_REQUEST';
export const GET_COORDINATES_SUCCESS = 'GET_COORDINATES_SUCCESS';
export const GET_COORDINATES_FAILURE = 'GET_COORDINATES_FAILURE';


export const GET_PRICE_PERCENTAGE_REQUEST = 'GET_PRICE_PERCENTAGE_REQUEST';
export const GET_PRICE_PERCENTAGE_SUCCESS = 'GET_PRICE_PERCENTAGE_SUCCESS';
export const GET_PRICE_PERCENTAGE_FAILURE = 'GET_PRICE_PERCENTAGE_FAILURE';

export const UNIT_REQUEST = 'UNIT_REQUEST';
export const UNIT_SUCCESS = 'UNIT_SUCCESS';
export const UNIT_FAILURE = 'UNIT_FAILURE';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';


export const LIST_DETAIL_REQUEST = 'LIST_DETAIL_REQUEST';
export const LIST_DETAIL_SUCCESS = 'LIST_DETAIL_SUCCESS';
export const LIST_DETAIL_FAILURE = 'LIST_DETAIL_FAILURE';

export const CAPTION_UPDATE_REQUEST = 'CAPTION_UPDATE_REQUEST';
export const CAPTION_UPDATE_SUCCESS = 'CAPTION_UPDATE_SUCCESS';
export const CAPTION_UPDATE_FAILURE = 'CAPTION_UPDATE_FAILURE';


export const PUBLISH_REQUEST = 'PUBLISH_REQUEST';
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_FAILURE = 'PUBLISH_FAILURE';


export const CLEAR_LIST_SPACE_STEPS = 'CLEAR_LIST_SPACE_STEPS';


export const LIST_ALL_SPACE_REQUEST = 'LIST_ALL_SPACE_REQUEST';
export const LIST_ALL_SPACE_SUCCESS = 'LIST_ALL_SPACE_SUCCESS';
export const LIST_ALL_SPACE_FAILURE = 'LIST_ALL_SPACE_FAILURE';


export const DRAFT_STATUS_REQUEST = 'DRAFT_STATUS_REQUEST';
export const DRAFT_STATUS_SUCCESS = 'DRAFT_STATUS_SUCCESS';
export const DRAFT_STATUS_FAILURE = 'DRAFT_STATUS_FAILURE';


export const SET_LIST_DETAIL_CLIENT = 'SET_LIST_DETAIL_CLIENT'; 
