export const STEP_ONE_SAVE = 'STEP_ONE_SAVE';
export const STEP_TWO_SAVE = 'STEP_TWO_SAVE';

export const STEP_THREE_SAVE_REQUEST = 'STEP_THREE_SAVE_REQUEST';
export const STEP_THREE_SAVE_SUCCESS = 'STEP_THREE_SAVE_SUCCESS';
export const STEP_THREE_SAVE_FAILURE = 'STEP_THREE_SAVE_FAILURE';


export const SPACE_TYPE_REQUEST = 'SPACE_TYPE_REQUEST';
export const SPACE_TYPE_SUCCESS = 'SPACE_TYPE_SUCCESS';
export const SPACE_TYPE_FAILURE = 'SPACE_TYPE_FAILURE';

export const SPACE_USED_FOR_REQUEST = 'SPACE_USED_FOR_REQUEST';
export const SPACE_USED_FOR_SUCCESS = 'SPACE_USED_FOR_SUCCESS';
export const SPACE_USED_FOR_FAILURE = 'SPACE_USED_FOR_FAILURE';


export const FEATURE_REQUEST = 'FEATURE_REQUEST';
export const FEATURE_SUCCESS = 'FEATURE_SUCCESS';
export const FEATURE_FAILURE = 'FEATURE_FAILURE';


export const FLOOR_REQUEST = 'FLOOR_REQUEST';
export const FLOOR_SUCCESS = 'FLOOR_SUCCESS';
export const FLOOR_FAILURE = 'FLOOR_FAILURE';


export const GET_COORDINATES_REQUEST = 'GET_COORDINATES_REQUEST';
export const GET_COORDINATES_SUCCESS = 'GET_COORDINATES_SUCCESS';
export const GET_COORDINATES_FAILURE = 'GET_COORDINATES_FAILURE';






