export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const NEARBY_REQUEST = 'NEARBY_REQUEST';
export const NEARBY_SUCCESS = 'NEARBY_SUCCESS';
export const NEARBY_FAILURE = 'NEARBY_FAILURE';


export const SEARCH_DETAILS_REQUEST = 'SEARCH_DETAILS_REQUEST';
export const SEARCH_DETAILS_SUCCESS = 'SEARCH_DETAILS_SUCCESS';
export const SEARCH_DETAILS_FAILURE = 'SEARCH_DETAILS_FAILURE';