export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const SEARCH_DETAILS_REQUEST = 'SEARCH_DETAILS_REQUEST';
export const SEARCH_DETAILS_SUCCESS = 'SEARCH_DETAILS_SUCCESS';
export const SEARCH_DETAILS_FAILURE =  'SEARCH_DETAILS_FAILURE';