export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_LIST = 'NOTIFICATION_LIST';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';

export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';

export const INSERT_NOTIFICATION = 'INSERT_NOTIFICATION';

export const UNSEEN_MESSAGE_REQUEST = 'UNSEEN_MESSAGE_REQUEST';
export const UNSEEN_MESSAGE_SUCCESS = 'UNSEEN_MESSAGE_SUCCESS';
export const UNSEEN_MESSAGE_FAILURE = 'UNSEEN_MESSAGE_FAILURE';


export const CLEAR_MESSAGE_REQUEST = 'CLEAR_MESSAGE_REQUEST';
export const CLEAR_MESSAGE_SUCCESS = 'CLEAR_MESSAGE_SUCCESS';
export const CLEAR_MESSAGE_FAILURE = 'CLEAR_MESSAGE_FAILURE'; 