export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_LIST = 'NOTIFICATION_LIST';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';

export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';

export const INSERT_NOTIFICATION = 'INSERT_NOTIFICATION';

