export const WALLET_REQUEST = 'WALLET_REQUEST';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';
export const WALLET_FAILURE = 'WALLET_FAILURE';

export const REFERRAL_LIST_REQUEST = 'REFERRAL_LIST_REQUEST';
export const REFERRAL_LIST_SUCCESS = 'REFERRAL_LIST_SUCCESS';
export const REFERRAL_LIST_FAILURE = 'REFERRAL_LIST_FAILURE';

export const REFERRAL_INVITE_REQUEST = 'REFERRAL_INVITE_REQUEST';
export const REFERRAL_INVITE_SUCCESS = 'REFERRAL_INVITE_SUCCESS';
export const REFERRAL_INVITE_FAILURE = 'REFERRAL_INVITE_FAILURE';



