export const DOCUMENT_REQUEST = 'DOCUMENT_REQUEST';
export const DOCUMENT_SUCCESS = 'DOCUMENT_SUCCESS';
export const DOCUMENT_FAILURE = 'DOCUMENT_FAILURE';

export const TOGGLE_DOCUMENT_DETAIL_MODAL = 'TOGGLE_DOCUMENT_DETAIL_MODAL';
export const TOGGLE_DOCUMENT_UPLOAD_MODAL = 'TOGGLE_DOCUMENT_UPLOAD_MODAL';
export const TOGGLE_VERIFY_ID_MODAL = 'TOGGLE_VERIFY_ID_MODAL';

export const VERIFY_LIST_REQUEST = 'VERIFY_LIST_REQUEST';
export const VERIFY_LIST_SUCCESS = 'VERIFY_LIST_SUCCESS';
export const VERIFY_LIST_FAILURE = 'VERIFY_LIST_FAILURE';

export const DOCUMENT_STEP_ONE_SAVE_REQUEST = 'DOCUMENT_STEP_ONE_SAVE_REQUEST';
export const DOCUMENT_STEP_ONE_SAVE_SUCCESS = 'DOCUMENT_STEP_ONE_SAVE_SUCCESS';
export const DOCUMENT_STEP_ONE_SAVE_FAILURE = 'DOCUMENT_STEP_ONE_SAVE_FAILURE';

export const DOC_UPLOAD_REQUEST = 'DOC_UPLOAD_REQUEST';
export const DOC_UPLOAD_SUCCESS = 'DOC_UPLOAD_SUCCESS';
export const DOC_UPLOAD_FAILURE = 'DOC_UPLOAD_FAILURE';

export const TOGGLE_MOBILE_VERIFY_MODAL = 'TOGGLE_MOBILE_VERIFY_MODAL';


export const MOBILE_VERIFY_REQUEST = 'MOBILE_VERIFY_REQUEST';
export const MOBILE_VERIFY_SUCCESS = 'MOBILE_VERIFY_SUCCESS';
export const MOBILE_VERIFY_FAILURE = 'MOBILE_VERIFY_FAILURE';



